name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: npmolino/bale_public_oshmem4.0.3:v1

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file oshmem/Dockerfile_bale_test --tag my-image-name:$(date +%s)
