name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file oshmem/Dockerfile_bale_test --tag bale_test:v1
    - name: Run the Docker image
      run: docker run bale_test:v1 cat /opt/baletemp/hi.txt
